In [17]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
arr1_1 = np.arange(0, 100)

# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
arr1_4 = np.random.randint(10, 51, (5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[34 40 35 42 13]
 [14 19 38 11 11]]


In [18]:
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed)
val2_1 = data[2, 3]

# 2.2 Extract the first row
row2_2 = data[0]

# 2.3 Extract the last column
col2_3 = data[:, 3]

# 2.4 Extract rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100
filtered_elements2_5 = data[data > 100]


print("Element at row 2, column 3:", val2_1)
print("\nFirst row:")
print(row2_2)
print("\nLast column:")
print(col2_3)
print("\nSub-array (rows 1-2, columns 0-1):")
print(sub_arr2_4)
print("\nElements greater than 100:")
print(filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
Element at row 2, column 3: 120

First row:
[10 20 30 40]

Last column:
[ 40  80 120 160]

Sub-array (rows 1-2, columns 0-1):
[[ 50  60]
 [ 90 100]]

Elements greater than 100:
[110 120 130 140 150 160]


In [19]:
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))

# 3.1 Create a new array where values less than 10 are replaced with 0
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count the number of even elements
even_count3_3 = np.count_nonzero(arr3_1 % 2 == 0)

print("Original Array:\n", arr3_1)
print("\nModified Array:\n", arr3_2)
print("\nNumber of even elements:", even_count3_3)


--- Task 3: Conditional Operations ---
Original Array:
 [[ 5  9  4  7 15]
 [19 16 18  1 10]
 [15 20 17 10 10]
 [ 7 17 18 15  8]]

Modified Array:
 [[ 0  0  0  0 15]
 [19 16 18  0 10]
 [15 20 17 10 10]
 [ 0 17 18 15  0]]

Number of even elements: 9


In [20]:
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1 Calculate the sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Calculate the mean of each column
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Find the maximum value in each row
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Calculate the standard deviation of the entire array
std4_4 = np.std(arr4_1)

print("Array:\n", arr4_1)
print("\nSum of all elements:", sum4_1)
print("Mean of each column:", mean_cols4_2)
print("Maximum value in each row:", max_rows4_3)
print("Standard deviation:", std4_4)


--- Task 4: Aggregation Functions ---
Array:
 [[10  5 12]
 [ 3  8 15]
 [20  7  4]]

Sum of all elements: 84
Mean of each column: [11.          6.66666667 10.33333333]
Maximum value in each row: [12 15 20]
Standard deviation: 5.2493385826745405


In [21]:
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)  # 1D array from 0 to 23

# 5.1 Reshape into a 4x6 array
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape into a 2x3x4 array
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten the 4x6 array
flattened_arr5_4 = reshaped_arr5_2.ravel()     # Returns a view
flattened_arr5_5 = reshaped_arr5_2.flatten()   # Returns a copy

print("Original Array:\n", arr5_1)
print("\n4x6 Reshaped Array:\n", reshaped_arr5_2)
print("\n2x3x4 Reshaped Array:\n", reshaped_arr5_3)
print("\nFlattened using ravel():\n", flattened_arr5_4)
print("\nFlattened using flatten():\n", flattened_arr5_5)


--- Task 5: Reshaping and Flattening ---
Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

4x6 Reshaped Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

2x3x4 Reshaped Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Flattened using ravel():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Flattened using flatten():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [22]:
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the scalar to every element
result6_1 = arr6_1 + scalar

# 6.2 Add the vector to each row
result6_2 = arr6_1 + vector

print("Original Array:\n", arr6_1)
print("\nAfter adding scalar (10):\n", result6_1)
print("\nAfter adding vector [100, 200, 300]:\n", result6_2)


--- Task 6: Broadcasting ---
Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After adding scalar (10):
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

After adding vector [100, 200, 300]:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [23]:
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a view and modify it
view_arr7 = original_arr7[:]
view_arr7[0] = 99

# 7.2 Create a copy and modify it
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("Original Array:", original_arr7)
print("View Array:", view_arr7)
print("Copy Array:", copy_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
Original Array: [99  2  3  4  5]
View Array: [99  2  3  4  5]
Copy Array: [99  2  3  4  0]


In [25]:
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertically stack arr8_a and arr8_b
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontally stack arr8_a and arr8_b
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Vertically stack vstack_arr8_1 and arr8_c
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split combined_arr8_3 into 3 parts
part1, part2, part3 = np.vsplit(combined_arr8_3, [2, 4])

print("Vertical Stack:\n", vstack_arr8_1)
print("\nHorizontal Stack:\n", hstack_arr8_2)
print("\nCombined Array:\n", combined_arr8_3)
print("\nPart 1:\n", part1)
print("\nPart 2:\n", part2)
print("\nPart 3:\n", part3)


--- Task 8: Stacking and Splitting Arrays ---
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Combined Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Part 1:
 [[1 2]
 [3 4]]

Part 2:
 [[5 6]
 [7 8]]

Part 3:
 [[ 9 10]]


In [27]:
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1 Sort arr9_1 in ascending order
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort arr9_2d along columns
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find the index where value 9 is present
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find the index of the maximum value
max_idx9_4 = np.argmax(arr9_1)

print("Original 1D Array:", arr9_1)
print("\nSorted 1D Array:", sorted_arr9_1)
print("\nOriginal 2D Array:\n", arr9_2d)
print("\nColumn-wise Sorted 2D Array:\n", sorted_cols9_2)
print("\nIndex of value 9:", idx9_3)
print("\nIndex of maximum value:", max_idx9_4)


--- Task 9: Sorting and Searching ---
Original 1D Array: [5 2 8 1 9 4 7 3 6]

Sorted 1D Array: [1 2 3 4 5 6 7 8 9]

Original 2D Array:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]

Column-wise Sorted 2D Array:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]

Index of value 9: (array([4]),)

Index of maximum value: 4
